FORMAT: 1A
HOST: http://teachers.odl.mit.edu/

# ccxcon

CCXCon is a simple API serves as an interface between edX running instances and different MIT apps.

## Group Courses

## Courses Collection [/coursexs]

### List All Courses [GET]

+ Response 200 (application/json)

### Create a New Course [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /coursexs/1016dd7e

    + Body

            {

            }

## Course [/coursexs/{course_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course


### Retrieve a Course [GET]

+ Response 200 (application/json)

        {

        }

### Delete Course [DELETE]

Deletes a course and all of its components and CCXs associated with it.

+ Response 204 (application/json)



### Partially update Course [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


### Update Course [PUT]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


## Group Modules

## Modules collection [/coursexs/{course_uuid}/modules]
+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course

### List All modules  for a given Course [GET]

+ Response 200 (application/json)

    + Body

            {

            }

### Create a New Module  [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /coursexs/1016dd7e/modules/bcfa43b4/

    + Body

            {

            }

## Module [/coursexs/{course_uuid}/modules/{module_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course
    + module_uuid: `bcfa43b4` (string, required) - UUID of the module


### Retrieve a Module [GET]

+ Response 200 (application/json)

        {

        }

### Delete a Module [DELETE]

Deletes a CCX course and all of its components associated with it.

+ Response 204 (application/json)



### Partially update a Module [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


### Update a Module [PUT]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


## Group CCXs

## CCX Collection [/coursexs/{course_uuid}/ccxs]
+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course

### List All CCXs  for a given Course [GET]

+ Response 200 (application/json)

    + Body

            {

            }


### Create a New CCX Course  [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /coursexs/1016dd7e/ccxs/bcfa43b4/

    + Body

            {

            }

## CCX [/coursexs/{course_uuid}/ccxs/{ccx_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course
    + ccx_uuid: `bcfa43b4` (string, required) - UUID of the ccx course


### Retrieve a CCX [GET]

+ Response 200 (application/json)

        {

        }

### Delete a CCX [DELETE]

Deletes a CCX course and all of its components associated with it.

+ Response 204 (application/json)



### Partially update a CCX [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


### Update a CCX [PUT]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


## Group CCX Modules

## Modules collection [/coursexs/{ccx_uuid}/modules]
+ Parameters
    + ccx_uuid: `1016dd7e` (string, required) - UUID of the CCX course

### List All modules associated with a given CCX [GET]

+ Response 200 (application/json)

    + Body

            {

            }

## Module membership [/ccxs/{ccx_uuid}/modues/{module_uuid}]

+ Parameters
    + ccx_uuid: `1016dd7e` (string, required) - UUID of the CCX course
    + module_uuid: `bcfa43b4` (string, required) - UUID of the module

### Add a module to a CCX Course  [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /ccxs/bcfa43b4/modules/40c35471

    + Body

            {

            }

### Delete a CCX [DELETE]

Deletes the association of a module from a CCX course.

+ Response 204 (application/json)
