FORMAT: 1A
HOST: http://teachers.odl.mit.edu/

# ccxcon

CCXCon is a simple API serves as an interface between edX running instances and different MIT apps.

## Group Courses

## Courses Collection [/coursexs]

### List All Courses [GET]

+ Response 200 (application/json)
+ Attribute (array[Course])

### Create a New Course [POST]

+ Request (application/json)

        {
          "title": "The Hobbit",
          "author": "Bilbo Baggins",
          "overview": "A hobbit fights some trolls then goes home.",
          "description": "test description",
          "video_url": "https://www.youtube.com/watch?v=ROor6_NGIWU",
          "modules": [
            {
              "title": "Gandalf comes to see Bilbo",
              "subchapters": ["test", "titles", "go", "here"]
            }
          ]
        }

+ Response 201 (application/json)
    + Attributes (Course)
    + Headers

            Location: /coursexs/1016dd7e

## Course [/coursexs/{course_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course

### Retrieve a Course [GET]

+ Response 200 (application/json)
  + Attributes (Course)

### Delete Course [DELETE]

Deletes a course and all of its components and CCXs associated with it.

+ Response 204 (application/json)

### Partially update Course [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)
  + Attributes (Course)


### Update Course [PUT]

+ Request (application/json)

        {
          "title": "The Hobbit",
          "author": "Bilbo Baggins",
          "overview": "A hobbit fights some trolls then goes home.",
          "description": "test description",
          "video_url": "https://www.youtube.com/watch?v=ROor6_NGIWU",
          "modules": [
            {
              "title": "Gandalf comes to see Bilbo",
              "subchapters": ["test", "titles", "go", "here"]
            }
          ]
        }

+ Response 200 (application/json)
  + Attributes (Course)


## Group Modules

## Modules collection [/coursexs/{course_uuid}/modules]
+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course

### List All modules  for a given Course [GET]

+ Response 200 (application/json)
    + Attributes (array[Module])

### Create a New Module  [POST]

+ Request (application/json)

            {
              "title": "Gandalf comes to see Bilbo",
              "subchapters": ["test", "titles", "go", "here"],
            }

+ Response 201 (application/json)
    + Attributes (Course)
    + Headers

            Location: /coursexs/1016dd7e/modules/bcfa43b4/

## Module [/coursexs/{course_uuid}/modules/{module_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course
    + module_uuid: `bcfa43b4` (string, required) - UUID of the module


### Retrieve a Module [GET]

+ Response 200 (application/json)
    + Attributes (Module)

### Delete a Module [DELETE]

Deletes a CCX course and all of its components associated with it.

+ Response 204 (application/json)

### Partially update a Module [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)
    + Attributes (Module)


### Update a Module [PUT]

+ Request (application/json)

            {
              "title": "Gandalf comes to see Bilbo",
              "subchapters": ["test", "titles", "go", "here"],
              "price_cents": 10000
            }

+ Response 200 (application/json)
    + Attributes (Module)


## Group CCXs

## CCX Collection [/coursexs/{course_uuid}/ccxs]
+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course

### List All CCXs  for a given Course [GET]

+ Response 200 (application/json)

    + Body

            {

            }


### Create a New CCX Course  [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /coursexs/1016dd7e/ccxs/bcfa43b4/

    + Body

            {

            }

## CCX [/coursexs/{course_uuid}/ccxs/{ccx_uuid}]

+ Parameters
    + course_uuid: `1016dd7e` (string, required) - UUID of the edX course
    + ccx_uuid: `bcfa43b4` (string, required) - UUID of the ccx course


### Retrieve a CCX [GET]

+ Response 200 (application/json)

        {

        }

### Delete a CCX [DELETE]

Deletes a CCX course and all of its components associated with it.

+ Response 204 (application/json)



### Partially update a CCX [PATCH]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


### Update a CCX [PUT]

+ Request (application/json)

            {

            }

+ Response 200 (application/json)

            {

            }


## Group CCX Modules

## Modules collection [/coursexs/{ccx_uuid}/modules]
+ Parameters
    + ccx_uuid: `1016dd7e` (string, required) - UUID of the CCX course

### List All modules associated with a given CCX [GET]

+ Response 200 (application/json)

    + Body

            {

            }

## Module membership [/ccxs/{ccx_uuid}/modules/{module_uuid}]

+ Parameters
    + ccx_uuid: `1016dd7e` (string, required) - UUID of the CCX course
    + module_uuid: `bcfa43b4` (string, required) - UUID of the module

### Add a module to a CCX Course  [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /ccxs/bcfa43b4/modules/40c35471

    + Body

            {

            }

### Delete a CCX [DELETE]

Deletes the association of a module from a CCX course.

+ Response 204 (application/json)


# Data Structures

## Course (object)
+ title: Introductory Physics: Classical Mechanics (string)
+ author: David E. Pritchard (string)
+ video_url (string)
+ terms_url (string)
+ overview (string)
+ description: This is a college-level Introductory Netwonian Mechanics (string)
+ resources (object)
    + modules (string) - url to list modules

## Module (object)
+ title (string)
+ price_cents: 1000 (number) - price in cents to avoid poor decimal support
+ pages (array[string]) - list of strings representing chapter pages
