db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate --noinput &&
    python manage.py runserver 0.0.0.0:8077'
  volumes:
    - .:/src
  environment:
    PORT: 8077
    DATABASE_URL: postgres://postgres@db:5432/postgres
    TOX_WORK_DIR: .tox
    COVERAGE_DIR: htmlcov
  ports:
    - "8077:8077"
  links:
    - db