db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate --noinput &&
    python manage.py runsslserver 0.0.0.0:8077'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    CCXCON_LOG_LEVEL: DEBUG
    DJANGO_LOG_LEVEL: INFO
    PORT: 8077
    DATABASE_URL: postgres://postgres@db:5432/postgres
    CCXCON_DB_DISABLE_SSL: 'True'
    ALLOWED_HOSTS:
    CCXCON_USE_CAS:
    CCXCON_ADMIN_EMAIL:
    CCXCON_CAS_URL:
    TOX_WORK_DIR: .tox
    COVERAGE_DIR: htmlcov
  ports:
    - "8077:8077"
  links:
    - db