# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField(max_length=255, unique=True)),
                ('oauth_client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('grant_token', models.CharField(blank=True, max_length=128, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=128, null=True)),
                ('access_token', models.CharField(blank=True, max_length=128, null=True)),
                ('access_token_expiration', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc))),
            ],
        ),
    ]
