# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backinginstance',
            name='username',
            field=models.CharField(blank=True, help_text='Username the backing oauth user is attached to. This is used to request course structure and MUST be a staff member of the course.', max_length=30, null=True),
        ),
    ]
