# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:40
# pylint: skip-file
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_edx_instance_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='edx_instance',
        ),
    ]
