# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# pylint: skip-file

def make_userinfo(apps, schema_editor):
    User = apps.get_model('auth.User')
    UserInfo = apps.get_model('courses.UserInfo')
    for user in User.objects.all():
        if not hasattr(user, 'info'):
            UserInfo.objects.create(user=user)

class Migration(migrations.Migration):

    replaces = [
        ('courses', '0004_userinfo'),
        ('courses', '0005_add_userinfo_for_old_users'),
        ('courses', '0002_video_url_to_image_url'),
        ('courses', '0004_merge'),
        ('courses', '0006_merge'),
        ('courses', '0007_edx_instance_optional')
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_remove_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edx_instance', models.URLField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            make_userinfo
        ),
        migrations.RenameField(
            model_name='course',
            old_name='video_url',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='edx_instance',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
