# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:41
# pylint: skip-file
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_edx_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='edx_instance_fk',
            new_name='edx_instance',
        ),
    ]
