# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_edx_uid_not_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxauthor',
            name='edx_uid',
            field=models.CharField(help_text='Unique ID generated by the edx-platform', max_length=32, unique=True),
        ),
    ]
