# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.TextField(help_text=b'course locator from edx', unique=False, null=True),
            preserve_default=False,
        ),
    ]
