# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 14:31
# pylint: skip-file
from __future__ import unicode_literals

from django.db import migrations


def instance_to_fk(apps, schema_editor):
    Course = apps.get_model('courses.Course')
    BackingInstance = apps.get_model('oauth_mgmt.BackingInstance')
    for course in Course.objects.all():
        bi, _ = BackingInstance.objects.get_or_create(instance_url=course.edx_instance)
        course.edx_instance_fk = bi
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userinfo_edx_instance_fk'),
    ]

    operations = [
        migrations.RunPython(instance_to_fk)
    ]
