# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 14:52
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def gen_uid(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.all():
        course.course_id = uuid.uuid4().hex
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_id'),
    ]

    operations = [
        migrations.RunPython(
            gen_uid, reverse_code=migrations.RunPython.noop
        ),
    ]
