# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_userinfo_edx_instance_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='edx_instance',
        ),
    ]
