# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_nullable_description_overview_author_name__unique_course_id'),
        ('courses', '0005_edx_uid_not_uuid'),
    ]

    operations = [
    ]
