# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_fk_on_edx_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
